before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  -
    env:
      - CGO_ENABLED=0
    main: ./main.go
    binary: rapid7-insightappsec-threadfix
    goos:
      - linux
      - windows
    goarch:
      - amd64
archives:
  -
    name_template: "{{ .ArtifactName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macOS
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format: zip
    wrap_in_directory: true
    files:
      - LICENSE
      - README.md
      - help.md
      - configs/settings.yml

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

